### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by rastalamm** [devdoc/SublimeLinter-jslint#7]
How can I use the below code (template strings) with jslint?

```
`${apiHost}/users/${user.id}/cart`
```

Keep on getting errors

**Comment by devdoc** [comment]
Right now, I don't think you can do that without some manual tweaking.

SublimeLinter-jslint uses [node-jslint](https://github.com/reid/node-jslint) to do the actual linting. `node-jslint` still uses the old jslint version by default, which doesn't support es6/es2015 syntax. `node-jslint` does provide command line options to use the new jslint which does support es6/es2015 syntax. However, the new version also uses 0-based line number indexing which will make Sublime Text show the error indicators on wrong lines (see issue #5).

You could try to manually tweak your linter installation (see issue #5 for details) or wait for the default behavior of `node-jslint` to change (the change has been announced and should be coming in `node-jslint` v1.0.0.

**Comment by devdoc** [comment]
node-jslint now supports a new option which can be used to enable es6/es2015 syntax support without breaking the error highlighting inside Sublime Text. See issue #5 for the solution.
