### ISSUE TITLE
how to use a specific jslint version

### ISSUE THREAD

**Issue by vuau** [devdoc/SublimeLinter-jslint#8]
The project which I am maintaining is using jslint edtion from 2010-12-21. How can I specify an jslint edition for SublimeLinter-jslint

**Comment by devdoc** [comment]
Sorry about the late response!

SublimeLinter-jslint is using node-jslint under the hoods to do the linting. You can specify command-line arguments that are used when executing the linter in `SublimeLinter.sublime-settings` (Preferences > Package Settings > SublimeLinter > Settings - User). I believe the appropriate changes are as follows:

```
            "jslint": {
                "@disable": false,
                "args": [
                    "--edition=2010-12-21"
                ],
                "excludes": []
            },
```

However, node-jslint [doesn't seem to include](https://github.com/reid/node-jslint/tree/master/lib) the edition you want, so you may have to copy the appropriate jslint edition to the appropriate folder (`<global npm modules folder>/npm/lib/`) yourself.
